name: Deploy to Render

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeyren/render-deploy-action@v1
        with:
          service-id: srv-da9icu9srm7s73cenkb0
          api-key: ${{ secrets.RENDER_API_KEY }}
